import { Link } from 'expo-router'
import { SafeAreaView, StyleSheet, Text, View } from 'react-native'
import { colors, typography } from '@/theme'

export default function TandemScreen() {
  return <SafeAreaView style={styles.safe}><View style={styles.container}><Link href="/" style={styles.back}>← Aujourd’hui</Link><Text style={styles.kicker}>CONVERSATION PRIVÉE</Text><Text style={styles.title}>Ton tandem</Text><View style={styles.avatar}><Text style={styles.avatarText}>É</Text></View><Text style={styles.name}>Élodie Martin</Text><Text style={styles.status}>● En ligne</Text><View style={styles.message}><Text style={styles.messageText}>Je pense à toi pour ta séance du jour.</Text><Text style={styles.time}>Hier · 21:14</Text></View><Text style={styles.private}>Les échanges restent privés entre vous.</Text></View></SafeAreaView>
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.paper }, container: { padding: 24, flex: 1 }, back: { color: colors.muted, fontFamily: typography.mono, fontSize: 11, marginBottom: 54 }, kicker: { color: colors.copper, fontFamily: typography.mono, fontSize: 10, letterSpacing: 1 }, title: { color: colors.ink, fontFamily: typography.display, fontSize: 42, marginTop: 16 }, avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.copper, justifyContent: 'center', alignItems: 'center', marginTop: 34 }, avatarText: { color: colors.white, fontFamily: typography.display, fontSize: 30 }, name: { color: colors.ink, fontFamily: typography.display, fontSize: 25, marginTop: 14 }, status: { color: colors.copper, fontFamily: typography.mono, fontSize: 10, marginTop: 6 }, message: { borderWidth: 1, borderColor: colors.line, padding: 18, marginTop: 36, maxWidth: 320 }, messageText: { color: colors.ink, fontSize: 16, lineHeight: 23 }, time: { color: colors.muted, fontFamily: typography.mono, fontSize: 9, marginTop: 12 }, private: { color: colors.muted, fontFamily: typography.mono, fontSize: 10, marginTop: 'auto' } })
