export type Locale = 'fr' | 'en'

export const copy = {
  fr: {
    eyebrow: 'AGAPEPLAY / TANDEM',
    greeting: 'Un petit pas, aujourd’hui.',
    subtitle: 'Un temps simple pour revenir à l’essentiel.',
    dailySession: 'Rituel du jour',
    theme: 'Présence',
    sessionTitle: 'Repartir avec Jésus',
    verse: '« Venez à moi, vous tous qui êtes fatigués… »',
    prompt: 'Qu’est-ce que tu peux déposer maintenant ?',
    start: 'Commencer',
    journey: 'Parcours',
    tandem: 'Tandem',
    journal: 'Journal privé',
    today: 'Aujourd’hui',
    saved: 'Votre espace reste privé.',
    offline: 'Hors ligne · vos actions seront synchronisées.',
    language: 'Langue',
  },
  en: {
    eyebrow: 'AGAPEPLAY / TANDEM',
    greeting: 'One small step, today.',
    subtitle: 'A simple moment to return to what matters.',
    dailySession: 'Daily ritual',
    theme: 'Presence',
    sessionTitle: 'Starting again with Jesus',
    verse: '“Come to me, all you who are weary…”',
    prompt: 'What can you lay down right now?',
    start: 'Begin',
    journey: 'Journey',
    tandem: 'Tandem',
    journal: 'Private journal',
    today: 'Today',
    saved: 'Your space stays private.',
    offline: 'Offline · your actions will sync later.',
    language: 'Language',
  },
} as const
