/**
 * Textes de l'interface web, par langue.
 *
 * Extrait d'App.tsx le 05/08/2026 : le fichier faisait 977 lignes, dont 272
 * pour ce seul objet. Le sortir rend les deux lisibles — et le jour où une
 * troisième langue arrive, elle se pose ici sans toucher à la logique.
 *
 * Déplacé dans packages/content le 05/08/2026, aux côtés des textes du mobile.
 * Les deux jeux restent distincts : voir shared.ts pour ce qu'ils ont
 * réellement en commun.
 */
import { sharedLabels } from './shared'

export const copy = {
  fr: {
    ...sharedLabels.fr,
    greeting: 'Bonjour, Claire',
    subtitle: 'Un petit pas, accompagné.',
    today: "Aujourd'hui",
    journal: 'Journal',
    continue: 'Commencer la séance',
    resume: 'Reprendre la séance',
    completed: 'Séance terminée',
    week: 'Semaine 1 sur 6',
    private: 'Privé par défaut',
    save: 'Garder dans mon journal',
    saved: 'Ajouté à ton journal',
    write: 'Écris ce que tu gardes de ce moment…',
    send: 'Envoyer',
    share: 'Partager avec Élodie',
    shared: 'Partagé avec Élodie',
    report: 'Signaler un problème',
    block: 'Bloquer cette relation',
    settings: 'Réglages',
    notifications: 'Notifications',
    emptyJournal: 'Ton journal est un espace à toi. Rien ne sera partagé sans ton choix.',
    reset: 'Réinitialiser la démo',
    mock: 'Mode démonstration',
    mockDescription: 'Les données sont locales à cet appareil. Les services réels seront branchés plus tard.',
    backendReady: 'Supabase prêt · mode démonstration',
    backendReadyDescription: 'Le projet distant est configuré. L’authentification et la synchronisation seront activées ensuite.',
    backendConnected: 'Supabase connecté',
    backendConnectedDescription: 'Ton parcours et ton journal privé peuvent maintenant être synchronisés.',
    signOut: 'Se déconnecter',
    email: 'Adresse email',
    magicLinkDescription: 'Reçois un lien de connexion unique, sans mot de passe.',
    sendMagicLink: 'Recevoir mon lien',
    continueWithGoogle: 'Continuer avec Google',
    continueWithMicrosoft: 'Continuer avec Microsoft',
    orEmail: 'ou avec ton email',
    magicLinkSent: 'Lien envoyé. Consulte ta boîte mail pour continuer.',
    authError: 'Impossible de se connecter pour le moment.',
    close: 'Fermer',
    syncError: 'La synchronisation a rencontré un problème. Tes données locales restent disponibles.',
    next: 'Prochaine étape',
    action: 'À mettre en pratique',
    encouragement: 'Écris un encouragement…',
    online: 'Actif',
    protected: 'Tes espaces privés restent privés.',
    reflection: 'Réflexion',
    yourTandem: 'Ton tandem',
    privateConversation: 'Conversation privée',
    privateOnly: 'Visible uniquement par toi',
    participant: 'Participant',
    encouragementMessage: 'Un espace pour s’encourager sans devenir un outil de surveillance.',
    tandemQuote: '« On avance ensemble. »',
    prayerPhrase: 'Je garde une phrase de prière pour ce soir.',
    yesterday: 'Hier',
    present: 'Présent',
    activeStatus: 'Actif',
    reportNotice: 'Signalement localisé dans cette démo. Il sera transmis à l’église et à AgapePlay dans la version connectée.',
    blockNotice: 'Le blocage supprimera immédiatement la relation dans la version connectée.',
    ritual: 'Rituel du jour',
    daysProgress: '3 repères sur 6',
    sessionRead: 'Recevoir',
    sessionReadDescription: 'Lis doucement. Rien à réussir, seulement un moment pour être présent.',
    sessionPractice: 'Répondre',
    sessionPracticeDescription: 'Garde une phrase, une image ou une prière qui vient maintenant.',
    sessionReflectionPlaceholder: 'J’écris ce que je veux garder…',
    optional: 'Facultatif',
    beginReflection: 'Prendre ce temps',
    finishSession: 'Terminer la séance',
    backToToday: 'Revenir à aujourd’hui',
    openJournal: 'Ouvrir mon journal',
    sessionComplete: 'Tu as pris ce temps.',
    sessionCompleteDescription: 'Ce petit pas compte. Tu peux le laisser ici, ou le partager avec ton tandem quand tu le souhaites.',
    leaveSession: 'Quitter la séance',
    trustTitle: 'Avant de commencer',
    trustDescription: 'AgapePlay garde tes espaces personnels privés. Confirme les points suivants pour continuer.',
    ageConfirm: 'J’ai 16 ans ou plus.',
    privacyConsent: 'J’accepte la politique de confidentialité et l’usage nécessaire de mes données pour faire fonctionner mon compte.',
    termsConsent: 'J’accepte les règles d’utilisation d’AgapePlay.',
    continueTrust: 'Continuer',
    trustRequired: 'Confirme les trois points pour continuer.',
    settingsTitle: 'Réglages du compte',
    accountStatus: 'Statut du compte',
    deleteAccount: 'Demander la suppression',
    deleteAccountDescription: 'Ta demande sera traitée selon la procédure de suppression documentée. Tes données locales restent disponibles jusqu’à confirmation.',
    requestDeletion: 'Demander la suppression',
    deletionRequested: 'Demande de suppression enregistrée.',
    cancel: 'Annuler',
    notificationDescription: 'Choisis les rappels qui te servent, séparément.',
    sessionNotifications: 'Séances quotidiennes',
    messageNotifications: 'Messages du tandem',
    churchNotifications: 'Vie de l’église',
    absenceNotifications: 'Rappel après une absence',
    mentor: 'Mentor',
    church: 'Église',
    workspacePending: 'Espace en préparation',
    mentorWorkspace: 'Espace mentor',
    churchWorkspace: 'Espace église',
    mentorVerification: 'Vérification du mentor',
    mentorTraining: 'Formation obligatoire',
    pendingStatus: 'En attente',
    requiredStatus: 'À commencer',
    verifiedStatus: 'Vérifié',
    completedStatus: 'Terminée',
    mentorPrivateRule: 'Les journaux privés et conversations restent invisibles au mentor par défaut.',
    mentorEmpty: 'Aucun participant ne t’est encore affecté.',
    churchEmpty: 'Aucune communauté n’est encore rattachée à ce compte.',
    churchGroups: 'Groupes actifs',
    aggregateStats: 'Statistiques anonymisées',
    aggregateStatsDescription: 'Les chiffres de communauté ne sont visibles que sous forme globale.',
    roleLabel: 'Rôle',
    memberRole: 'Membre',
    mentorRole: 'Mentor',
    leaderRole: 'Responsable',
    adminRole: 'Administrateur',
    groupsLabel: 'groupes',
    statsEmpty: 'Les premières statistiques apparaîtront quand la communauté aura une activité suffisante.',
    invite: 'Inviter mon tandem',
    inviteDescription: 'L’invitation est privée et expire après 7 jours.',
    inviteEmail: 'Email de la personne',
    createInvite: 'Créer l’invitation',
    inviteCreated: 'Invitation créée. Tu peux partager ce lien.',
    copyInvite: 'Copier le lien',
    inviteRequiresAuth: 'Connecte-toi pour créer une invitation privée.',
    inviteAccepted: 'Invitation acceptée. Ton tandem est actif.',
    inviteAcceptError: 'Cette invitation est invalide, expirée ou réservée à une autre adresse.',
    blockedStatus: 'Bloqué',
    blockedNotice: 'Cette relation est maintenant bloquée.',
    reportSent: 'Signalement transmis à la modération.',
    messageUnavailable: 'La conversation est indisponible pour le moment.',
    offline: 'Hors connexion · les changements seront synchronisés au retour.',
  },
  en: {
    ...sharedLabels.en,
    greeting: 'Good morning, Claire',
    subtitle: 'One small step, with someone beside you.',
    today: 'Today',
    journal: 'Journal',
    continue: 'Start session',
    resume: 'Resume session',
    completed: 'Session completed',
    week: 'Week 1 of 6',
    private: 'Private by default',
    save: 'Keep in my journal',
    saved: 'Added to your journal',
    write: 'Write what you are taking from this moment…',
    send: 'Send',
    share: 'Share with Elodie',
    shared: 'Shared with Elodie',
    report: 'Report a problem',
    block: 'Block this relationship',
    settings: 'Settings',
    notifications: 'Notifications',
    emptyJournal: 'Your journal is yours. Nothing is shared without your choice.',
    reset: 'Reset demo',
    mock: 'Demo mode',
    mockDescription: 'Data is local to this device. Real services will be connected later.',
    backendReady: 'Supabase ready · demo mode',
    backendReadyDescription: 'The remote project is configured. Authentication and sync will be enabled next.',
    backendConnected: 'Supabase connected',
    backendConnectedDescription: 'Your journey and private journal can now be synchronized.',
    signOut: 'Sign out',
    email: 'Email address',
    magicLinkDescription: 'Receive a one-time sign-in link, with no password.',
    sendMagicLink: 'Send my link',
    continueWithGoogle: 'Continue with Google',
    continueWithMicrosoft: 'Continue with Microsoft',
    orEmail: 'or with your email',
    magicLinkSent: 'Link sent. Check your inbox to continue.',
    authError: 'Unable to sign in right now.',
    close: 'Close',
    syncError: 'Sync ran into a problem. Your local data is still available.',
    next: 'Next step',
    action: 'Put it into practice',
    encouragement: 'Write an encouragement…',
    online: 'Active',
    protected: 'Your private spaces stay private.',
    reflection: 'Reflection',
    yourTandem: 'Your tandem',
    privateConversation: 'Private conversation',
    privateOnly: 'Visible only to you',
    participant: 'Participant',
    encouragementMessage: 'A space to encourage one another without becoming a monitoring tool.',
    tandemQuote: '“We are moving forward together.”',
    prayerPhrase: 'I am keeping one sentence of prayer for tonight.',
    yesterday: 'Yesterday',
    present: 'Present',
    activeStatus: 'Active',
    reportNotice: 'This demo keeps the report local. In the connected version, it will be sent to the church and AgapePlay.',
    blockNotice: 'Blocking will immediately remove the relationship in the connected version.',
    ritual: 'Today’s ritual',
    daysProgress: '3 markers out of 6',
    sessionRead: 'Receive',
    sessionReadDescription: 'Read slowly. There is nothing to achieve, only a moment to be present.',
    sessionPractice: 'Respond',
    sessionPracticeDescription: 'Keep one sentence, image, or prayer that comes to you now.',
    sessionReflectionPlaceholder: 'Write what you want to keep…',
    optional: 'Optional',
    beginReflection: 'Take this time',
    finishSession: 'Finish session',
    backToToday: 'Back to today',
    openJournal: 'Open my journal',
    sessionComplete: 'You took this time.',
    sessionCompleteDescription: 'This small step matters. Keep it here, or share it with your tandem when you are ready.',
    leaveSession: 'Leave session',
    trustTitle: 'Before you begin',
    trustDescription: 'AgapePlay keeps your personal spaces private. Confirm the following to continue.',
    ageConfirm: 'I am 16 or older.',
    privacyConsent: 'I accept the privacy policy and the data use needed to operate my account.',
    termsConsent: 'I accept AgapePlay’s terms of use.',
    continueTrust: 'Continue',
    trustRequired: 'Confirm all three points to continue.',
    settingsTitle: 'Account settings',
    accountStatus: 'Account status',
    deleteAccount: 'Request deletion',
    deleteAccountDescription: 'Your request will follow the documented deletion process. Local data stays available until confirmation.',
    requestDeletion: 'Request deletion',
    deletionRequested: 'Deletion request recorded.',
    cancel: 'Cancel',
    notificationDescription: 'Choose the reminders that serve you, separately.',
    sessionNotifications: 'Daily sessions',
    messageNotifications: 'Tandem messages',
    churchNotifications: 'Church life',
    absenceNotifications: 'Reminder after absence',
    mentor: 'Mentor',
    church: 'Church',
    workspacePending: 'Workspace in preparation',
    mentorWorkspace: 'Mentor workspace',
    churchWorkspace: 'Church workspace',
    mentorVerification: 'Mentor verification',
    mentorTraining: 'Required training',
    pendingStatus: 'Pending',
    requiredStatus: 'To begin',
    verifiedStatus: 'Verified',
    completedStatus: 'Completed',
    mentorPrivateRule: 'Private journals and conversations remain hidden from mentors by default.',
    mentorEmpty: 'No participant is assigned to you yet.',
    churchEmpty: 'No community is linked to this account yet.',
    churchGroups: 'Active groups',
    aggregateStats: 'Anonymous statistics',
    aggregateStatsDescription: 'Community numbers are only shown in aggregate form.',
    roleLabel: 'Role',
    memberRole: 'Member',
    mentorRole: 'Mentor',
    leaderRole: 'Leader',
    adminRole: 'Administrator',
    groupsLabel: 'groups',
    statsEmpty: 'The first statistics will appear once the community has enough activity.',
    invite: 'Invite my tandem',
    inviteDescription: 'The invitation is private and expires after 7 days.',
    inviteEmail: 'Person’s email',
    createInvite: 'Create invitation',
    inviteCreated: 'Invitation created. You can share this link.',
    copyInvite: 'Copy link',
    inviteRequiresAuth: 'Sign in to create a private invitation.',
    inviteAccepted: 'Invitation accepted. Your tandem is active.',
    inviteAcceptError: 'This invitation is invalid, expired, or reserved for another email.',
    blockedStatus: 'Blocked',
    blockedNotice: 'This relationship is now blocked.',
    reportSent: 'Report sent to moderation.',
    messageUnavailable: 'The conversation is unavailable right now.',
    offline: 'Offline · changes will sync when you are back online.',
  },
} as const

export type Copy = (typeof copy)['fr'] | (typeof copy)['en']
