/**
 * Textes de l'interface web, par langue.
 *
 * Extrait d'App.tsx le 05/08/2026 : le fichier faisait 977 lignes, dont 272
 * pour ce seul objet. Le sortir rend les deux lisibles — et le jour où une
 * troisième langue arrive, elle se pose ici sans toucher à la logique.
 *
 * Déplacé dans packages/content le 05/08/2026, aux côtés des textes du mobile.
 * Les deux jeux restent distincts : voir shared.ts pour ce qu'ils ont
 * réellement en commun.
 */
import { sharedLabels } from './shared'

export const copy = {
  fr: {
    ...sharedLabels.fr,
    greeting: 'Bonjour',
    subtitle: 'Un petit pas, accompagné.',
    journal: 'Journal',
    continue: 'Commencer la séance',
    resume: 'Reprendre la séance',
    completed: 'Séance terminée',
    week: 'Semaine 1 sur 6',
    private: 'Privé par défaut',
    save: 'Garder dans mon journal',
    saved: 'Ajouté à ton journal',
    write: 'Écris ce que tu gardes de ce moment…',
    send: 'Envoyer',
    share: 'Ouvrir la conversation',
    report: 'Signaler un problème',
    block: 'Bloquer cette relation',
    settings: 'Réglages',
    notifications: 'Notifications',
    emptyJournal: 'Ton journal est un espace à toi. Rien ne sera partagé sans ton choix.',
    reset: 'Réinitialiser la démo',
    mock: 'Mode démonstration',
    mockDescription: 'Les données sont locales à cet appareil. Les services réels seront branchés plus tard.',
    backendReady: 'Supabase prêt · mode démonstration',
    backendReadyDescription: 'Le projet distant est configuré. L’authentification et la synchronisation seront activées ensuite.',
    backendConnected: 'Supabase connecté',
    backendConnectedDescription: 'Ton parcours et ton journal privé peuvent maintenant être synchronisés.',
    signOut: 'Se déconnecter',
    email: 'Adresse email',
    magicLinkDescription: 'Reçois un lien de connexion unique, sans mot de passe.',
    sendMagicLink: 'Recevoir mon lien',
    continueWithGoogle: 'Continuer avec Google',
    continueWithMicrosoft: 'Continuer avec Microsoft',
    orEmail: 'ou avec ton email',
    magicLinkSent: 'Lien envoyé. Consulte ta boîte mail pour continuer.',
    authError: 'Impossible de se connecter pour le moment.',
    close: 'Fermer',
    syncError: 'La synchronisation a rencontré un problème. Tes données locales restent disponibles.',
    next: 'Prochaine étape',
    action: 'À mettre en pratique',
    encouragement: 'Écris un encouragement…',
    online: 'Actif',
    protected: 'Tes espaces privés restent privés.',
    reflection: 'Réflexion',
    yourTandem: 'Ton tandem',
    privateConversation: 'Conversation privée',
    privateOnly: 'Visible uniquement par toi',
    participant: 'Participant',
    encouragementMessage: 'Un espace pour s’encourager sans devenir un outil de surveillance.',
    tandemRole: 'Tandem de confiance',
    noTandemYet: 'Personne n’est encore apparié. Invite ta personne de confiance.',
    emptyThread: 'Aucun message pour l’instant. Le premier peut venir de toi.',
    present: 'Présent',
    activeStatus: 'Actif',
    reportNotice: 'Signalement localisé dans cette démo. Il sera transmis à l’église et à AgapePlay dans la version connectée.',
    blockNotice: 'Le blocage supprimera immédiatement la relation dans la version connectée.',
    ritual: 'Rituel du jour',
    daysProgress: '3 repères sur 6',
    sessionRead: 'Recevoir',
    sessionReadDescription: 'Lis doucement. Rien à réussir, seulement un moment pour être présent.',
    sessionPractice: 'Répondre',
    sessionPracticeDescription: 'Garde une phrase, une image ou une prière qui vient maintenant.',
    sessionReflectionPlaceholder: 'J’écris ce que je veux garder…',
    optional: 'Facultatif',
    beginReflection: 'Prendre ce temps',
    finishSession: 'Terminer la séance',
    backToToday: 'Revenir à aujourd’hui',
    openJournal: 'Ouvrir mon journal',
    sessionComplete: 'Tu as pris ce temps.',
    sessionCompleteDescription: 'Ce petit pas compte. Tu peux le laisser ici, ou le partager avec ton tandem quand tu le souhaites.',
    leaveSession: 'Quitter la séance',
    trustTitle: 'Avant de commencer',
    trustDescription: 'AgapePlay garde tes espaces personnels privés. Confirme les points suivants pour continuer.',
    ageConfirm: 'J’ai 16 ans ou plus.',
    privacyConsent: 'J’accepte la politique de confidentialité et l’usage nécessaire de mes données pour faire fonctionner mon compte.',
    termsConsent: 'J’accepte les règles d’utilisation d’AgapePlay.',
    continueTrust: 'Continuer',
    trustRequired: 'Confirme les trois points pour continuer.',
    settingsTitle: 'Réglages du compte',
    accountStatus: 'Statut du compte',
    exportData: 'Télécharger mes données',
    exportDescription: 'Un fichier avec ton profil, ta progression, ton journal, les messages que tu as envoyés et tes invitations.',
    exportReady: 'Fichier téléchargé.',
    exportFailed: 'On n’a pas pu rassembler toutes tes données. Rien n’a été téléchargé : réessaie dans un moment.',
    signOutEverywhere: 'Me déconnecter partout',
    signOutEverywhereDescription: 'Ferme ta session sur tous les appareils où tu es resté·e connecté·e.',
    signedOutEverywhere: 'Tu es déconnecté·e de tous tes appareils.',
    deleteAccount: 'Supprimer mon compte',
    deleteAccountDescription: 'C’est définitif. L’écran suivant dit exactement ce qui disparaît et ce qui reste.',
    deleteConfirmTitle: 'Supprimer ton compte, pour de bon',
    deleteConfirmErases: 'Ce qui disparaît : ton nom, ton adresse e-mail, ton journal, ta progression, tes préférences et tes invitations.',
    deleteConfirmKeeps: 'Ce qui reste : les messages que tu as envoyés restent dans la conversation de ton binôme. Ton nom, lui, disparaît : son écran indiquera que ce compte a été supprimé. Un signalement déjà déposé reste aussi, parce qu’il protège quelqu’un.',
    deleteConfirmBlocked: 'Si tu as bloqué quelqu’un, le blocage tient toujours après ton départ.',
    deleteConfirmSession: 'Tu seras déconnecté·e de tous tes appareils et ce compte ne pourra plus se connecter. Tu pourras revenir un jour avec la même adresse : ce sera un compte neuf, vide.',
    deleteConfirmExportFirst: 'Tu veux garder une trace ? Télécharge tes données avant.',
    deleteConfirmUnderstood: 'J’ai lu ce qui va se passer, et je veux supprimer mon compte.',
    deleteConfirm: 'Supprimer définitivement',
    deleteCancel: 'Non, revenir en arrière',
    deleteDone: 'Ton compte est supprimé.',
    deleteFailed: 'La suppression n’a pas abouti : rien n’a été supprimé. Réessaie, ou écris-nous.',
    cancel: 'Annuler',
    notificationDescription: 'Choisis les rappels qui te servent, séparément.',
    sessionNotifications: 'Séances quotidiennes',
    messageNotifications: 'Messages du tandem',
    churchNotifications: 'Vie de l’église',
    absenceNotifications: 'Rappel après une absence',
    mentor: 'Mentor',
    church: 'Église',
    workspacePending: 'Espace en préparation',
    mentorWorkspace: 'Espace mentor',
    churchWorkspace: 'Espace église',
    mentorVerification: 'Vérification du mentor',
    mentorTraining: 'Formation obligatoire',
    pendingStatus: 'En attente',
    requiredStatus: 'À commencer',
    verifiedStatus: 'Vérifié',
    completedStatus: 'Terminée',
    mentorPrivateRule: 'Les journaux privés et conversations restent invisibles au mentor par défaut.',
    mentorEmpty: 'Aucun participant ne t’est encore affecté.',
    churchEmpty: 'Aucune communauté n’est encore rattachée à ce compte.',
    churchGroups: 'Groupes actifs',
    aggregateStats: 'Statistiques anonymisées',
    aggregateStatsDescription: 'Les chiffres de communauté ne sont visibles que sous forme globale.',
    roleLabel: 'Rôle',
    memberRole: 'Membre',
    mentorRole: 'Mentor',
    leaderRole: 'Responsable',
    adminRole: 'Administrateur',
    groupsLabel: 'groupes',
    statsEmpty: 'Les premières statistiques apparaîtront quand la communauté aura une activité suffisante.',
    invite: 'Inviter mon tandem',
    inviteDescription: 'L’invitation est privée et expire après 7 jours.',
    inviteEmail: 'Email de la personne',
    createInvite: 'Créer l’invitation',
    inviteCreated: 'Invitation créée. Tu peux partager ce lien.',
    copyInvite: 'Copier le lien',
    inviteRequiresAuth: 'Connecte-toi pour créer une invitation privée.',
    inviteAccepted: 'Invitation acceptée. Ton tandem est actif.',
    inviteAcceptError: 'Cette invitation est invalide, expirée ou réservée à une autre adresse.',
    blockedStatus: 'Bloqué',
    endedStatus: 'Terminé',
    partnerDeleted: 'Ce compte a été supprimé',
    tandemEndedNote: 'Cette relation est terminée : personne ne peut plus y écrire. Les messages restent lisibles, et tu peux inviter quelqu’un d’autre quand tu veux.',
    blockedNotice: 'Cette relation est maintenant bloquée.',
    // Le refus silencieux : un UPDATE écarté par un `using` ne lève rien, il
    // touche zéro ligne. Sans ces deux phrases, l'écran annoncerait un blocage
    // que la base n'a pas posé. `syncError` ne convient pas — le serveur a bien
    // répondu. Même phrase que le mobile (`mobile-tandem.ts`) au geste de sortie
    // près : là-bas on revient sur l'écran, ici on recharge la page — c'est ce
    // qui relance le scan du tandem, et promettre l'autre serait promettre un
    // geste qui ne rafraîchit rien.
    blockRefused: 'Le blocage n’a pas été posé. Recharge la page pour voir où en est la relation.',
    unblockRefused: 'Le blocage n’a pas été levé. Recharge la page pour voir où en est la relation.',
    unblock: 'Lever le blocage',
    unblockOwnerNote: 'Tu as bloqué cette relation. Toi seul peux la lever.',
    unblockOtherNote: 'Cette relation a été bloquée par ton tandem. Seule la personne qui a posé le blocage peut la lever.',
    unblockFrozenNote: 'Ce blocage a été posé avant notre mise à jour de sécurité : l’application ne sait plus qui l’a posé, et ne peut donc le lever pour personne. Écris à contact@agapeplay.com pour qu’une personne s’en charge.',
    unblockTitle: 'Lever ce blocage ?',
    unblockDescription: 'La conversation redevient possible dans les deux sens : vous pourrez de nouveau vous écrire, et l’historique redevient lisible pour vous deux.',
    unblockReversible: 'Rien n’est définitif : tu pourras bloquer de nouveau quand tu le veux.',
    unblockConfirm: 'Oui, lever le blocage',
    unblockCancel: 'Non, garder le blocage',
    unblockedNotice: 'Le blocage est levé. La conversation reprend.',
    reportSent: 'Signalement transmis à la modération.',
    messageUnavailable: 'La conversation est indisponible pour le moment.',
    offline: 'Hors connexion · les changements seront synchronisés au retour.',

    // Le suivi des invitations. Le vocabulaire fuit « révoquer », qui est le
    // mot de la colonne `status` et de personne d'autre : on annule une
    // invitation. L'état affiché croise `status` et `expires_at` — jamais le
    // statut seul, rien ne le faisant passer à « expired » (voir
    // packages/domain/src/invitations.ts).
    invitationsKicker: 'Suivi',
    invitationsTitle: 'Tes invitations',
    invitationsDescription: 'Ce que tu as envoyé, où ça en est, et ce que tu peux encore reprendre.',
    invitationsLoading: 'Lecture de tes invitations…',
    invitationsError: 'Tes invitations n’ont pas pu être lues. Réessaie dans un instant.',
    invitationsRefresh: 'Relire la liste',
    invitationsSent: 'Envoyées',
    invitationsEmpty: 'Tu n’as encore invité personne.',
    invitationsReceived: 'Reçues',
    invitationsReceivedOne: 'Une invitation t’attend.',
    invitationsReceivedHint: 'Pour l’accepter, ouvre le lien reçu dans ton e-mail : c’est lui qui porte le code.',
    invitationsReceivedNoIdentity: 'Une invitation ne dit pas qui l’envoie tant qu’elle n’est pas acceptée. L’e-mail que tu as reçu, lui, le dit.',
    invitationStateLive: 'En attente de réponse',
    invitationStateExpired: 'Expirée',
    invitationStateAccepted: 'Acceptée',
    invitationStateRevoked: 'Annulée',
    invitationsSentOn: 'Envoyée le',
    invitationsExpiresOn: 'Valable jusqu’au',
    invitationsExpiredOn: 'Expirée le',
    invitationsAcceptedOn: 'Acceptée le',
    invitationsCancel: 'Annuler cette invitation',
    invitationsCancelled: 'Invitation annulée. Le lien ne fonctionne plus.',
    invitationsCancelFailed: 'L’invitation n’a pas pu être annulée. Relis la liste : son état a peut-être changé entre-temps.',
    invitationsExpiredNote: 'Ce lien ne fonctionne plus. Envoie une nouvelle invitation si tu veux réessayer.',
    invitationsBlockedNote: 'Cette personne et toi êtes en blocage : l’application ne peut plus toucher à cette invitation. Elle ne mène nulle part — l’appariement est refusé tant que le blocage tient — et elle s’éteindra d’elle-même à sa date. Pour la reprendre en main, il faut d’abord lever le blocage.',

    // Espace modérateur. Le vocabulaire évite « dossier à traiter » au profit
    // de ce qui se passe réellement : quelqu'un a écrit qu'il ne va pas bien
    // dans une relation, et quelqu'un d'autre doit décider. Rien ici ne nomme
    // les personnes — l'interface n'en dispose pas, et c'est voulu.
    moderation: 'Modération',
    moderationTitle: 'Signalements',
    moderationDescription: 'Ce qui a été signalé, son contexte, et rien d’autre.',
    moderationLoading: 'Lecture des signalements…',
    moderationError: 'Les signalements n’ont pas pu être lus. Réessaie dans un instant.',
    moderationEmpty: 'Aucun signalement n’attend de décision.',
    moderationRefresh: 'Relire la liste',
    moderationNoIdentity: 'Cet espace ne montre ni les noms ni les comptes des participants : c’est une décision de conception, pas un manque.',
    moderationCount: 'signalements',
    moderationOpenCount: 'en attente de décision',
    statusOpen: 'À traiter',
    statusReviewing: 'Pris en charge',
    statusResolved: 'Clos',
    moderationTake: 'Prendre en charge',
    moderationClose: 'Clore le dossier',
    moderationReopen: 'Rouvrir le dossier',
    moderationUpdated: 'Décision enregistrée.',
    moderationUpdateFailed: 'La décision n’a pas été enregistrée. Ton accès à la modération a peut-être été retiré entre-temps.',
    moderationReason: 'Ce qui est écrit dans le signalement',
    moderationReportedAt: 'Signalé le',
    moderationClosedAt: 'Clos le',
    moderationMessage: 'Le message signalé',
    moderationNoMessage: 'Ce signalement ne vise aucun message précis : il porte sur la relation. Le reste de la conversation n’est pas lisible d’ici.',
    moderationFromReporter: 'Écrit par la personne qui signale',
    moderationFromOther: 'Écrit par l’autre participant',
    moderationContext: 'La relation',
    moderationNoContext: 'L’état de cette relation n’est pas lisible : elle a sans doute été supprimée.',
    moderationRelationOpened: 'Ouverte le',
    moderationRelationBlocked: 'Bloquée le',
    moderationRelationEnded: 'Terminée le',
    relationActive: 'Relation active',
    relationBlocked: 'Relation bloquée',
    relationPaused: 'Relation en pause',
    relationEnded: 'Relation terminée',
    moderationTrail: 'Journal des décisions',
    moderationTrailEmpty: 'Aucune décision n’a encore été prise sur ce dossier.',
    moderationTrailNote: 'Seules les décisions laissent une trace. Ouvrir un dossier n’en laisse aucune.',
    moderationTrailByMe: 'par toi',
    moderationTrailByOther: 'par un autre modérateur',
    moderationTrailUnknown: 'sans modérateur identifié',
  },
  en: {
    ...sharedLabels.en,
    greeting: 'Good morning',
    subtitle: 'One small step, with someone beside you.',
    journal: 'Journal',
    continue: 'Start session',
    resume: 'Resume session',
    completed: 'Session completed',
    week: 'Week 1 of 6',
    private: 'Private by default',
    save: 'Keep in my journal',
    saved: 'Added to your journal',
    write: 'Write what you are taking from this moment…',
    send: 'Send',
    share: 'Open the conversation',
    report: 'Report a problem',
    block: 'Block this relationship',
    settings: 'Settings',
    notifications: 'Notifications',
    emptyJournal: 'Your journal is yours. Nothing is shared without your choice.',
    reset: 'Reset demo',
    mock: 'Demo mode',
    mockDescription: 'Data is local to this device. Real services will be connected later.',
    backendReady: 'Supabase ready · demo mode',
    backendReadyDescription: 'The remote project is configured. Authentication and sync will be enabled next.',
    backendConnected: 'Supabase connected',
    backendConnectedDescription: 'Your journey and private journal can now be synchronized.',
    signOut: 'Sign out',
    email: 'Email address',
    magicLinkDescription: 'Receive a one-time sign-in link, with no password.',
    sendMagicLink: 'Send my link',
    continueWithGoogle: 'Continue with Google',
    continueWithMicrosoft: 'Continue with Microsoft',
    orEmail: 'or with your email',
    magicLinkSent: 'Link sent. Check your inbox to continue.',
    authError: 'Unable to sign in right now.',
    close: 'Close',
    syncError: 'Sync ran into a problem. Your local data is still available.',
    next: 'Next step',
    action: 'Put it into practice',
    encouragement: 'Write an encouragement…',
    online: 'Active',
    protected: 'Your private spaces stay private.',
    reflection: 'Reflection',
    yourTandem: 'Your tandem',
    privateConversation: 'Private conversation',
    privateOnly: 'Visible only to you',
    participant: 'Participant',
    encouragementMessage: 'A space to encourage one another without becoming a monitoring tool.',
    tandemRole: 'Trusted tandem',
    noTandemYet: 'No one is paired yet. Invite your trusted person.',
    emptyThread: 'No messages yet. The first one can come from you.',
    present: 'Present',
    activeStatus: 'Active',
    reportNotice: 'This demo keeps the report local. In the connected version, it will be sent to the church and AgapePlay.',
    blockNotice: 'Blocking will immediately remove the relationship in the connected version.',
    ritual: 'Today’s ritual',
    daysProgress: '3 markers out of 6',
    sessionRead: 'Receive',
    sessionReadDescription: 'Read slowly. There is nothing to achieve, only a moment to be present.',
    sessionPractice: 'Respond',
    sessionPracticeDescription: 'Keep one sentence, image, or prayer that comes to you now.',
    sessionReflectionPlaceholder: 'Write what you want to keep…',
    optional: 'Optional',
    beginReflection: 'Take this time',
    finishSession: 'Finish session',
    backToToday: 'Back to today',
    openJournal: 'Open my journal',
    sessionComplete: 'You took this time.',
    sessionCompleteDescription: 'This small step matters. Keep it here, or share it with your tandem when you are ready.',
    leaveSession: 'Leave session',
    trustTitle: 'Before you begin',
    trustDescription: 'AgapePlay keeps your personal spaces private. Confirm the following to continue.',
    ageConfirm: 'I am 16 or older.',
    privacyConsent: 'I accept the privacy policy and the data use needed to operate my account.',
    termsConsent: 'I accept AgapePlay’s terms of use.',
    continueTrust: 'Continue',
    trustRequired: 'Confirm all three points to continue.',
    settingsTitle: 'Account settings',
    accountStatus: 'Account status',
    exportData: 'Download my data',
    exportDescription: 'One file with your profile, your progress, your journal, the messages you sent and your invitations.',
    exportReady: 'File downloaded.',
    exportFailed: 'We could not gather all of your data. Nothing was downloaded — try again in a moment.',
    signOutEverywhere: 'Sign me out everywhere',
    signOutEverywhereDescription: 'Close your session on every device where you stayed signed in.',
    signedOutEverywhere: 'You are signed out on all your devices.',
    deleteAccount: 'Delete my account',
    deleteAccountDescription: 'This is permanent. The next screen says exactly what goes and what stays.',
    deleteConfirmTitle: 'Delete your account, for good',
    deleteConfirmErases: 'What goes: your name, your email address, your journal, your progress, your preferences and your invitations.',
    deleteConfirmKeeps: 'What stays: the messages you sent stay in your partner’s conversation. Your name does not: their screen will say this account was deleted. A report already filed stays too, because it protects someone.',
    deleteConfirmBlocked: 'If you blocked someone, that block still holds after you leave.',
    deleteConfirmSession: 'You will be signed out on every device, and this account will not be able to sign in again. You can come back one day with the same address: it will be a new, empty account.',
    deleteConfirmExportFirst: 'Want to keep a copy? Download your data first.',
    deleteConfirmUnderstood: 'I have read what will happen, and I want to delete my account.',
    deleteConfirm: 'Delete permanently',
    deleteCancel: 'No, take me back',
    deleteDone: 'Your account is deleted.',
    deleteFailed: 'The deletion did not go through: nothing was deleted. Try again, or write to us.',
    cancel: 'Cancel',
    notificationDescription: 'Choose the reminders that serve you, separately.',
    sessionNotifications: 'Daily sessions',
    messageNotifications: 'Tandem messages',
    churchNotifications: 'Church life',
    absenceNotifications: 'Reminder after absence',
    mentor: 'Mentor',
    church: 'Church',
    workspacePending: 'Workspace in preparation',
    mentorWorkspace: 'Mentor workspace',
    churchWorkspace: 'Church workspace',
    mentorVerification: 'Mentor verification',
    mentorTraining: 'Required training',
    pendingStatus: 'Pending',
    requiredStatus: 'To begin',
    verifiedStatus: 'Verified',
    completedStatus: 'Completed',
    mentorPrivateRule: 'Private journals and conversations remain hidden from mentors by default.',
    mentorEmpty: 'No participant is assigned to you yet.',
    churchEmpty: 'No community is linked to this account yet.',
    churchGroups: 'Active groups',
    aggregateStats: 'Anonymous statistics',
    aggregateStatsDescription: 'Community numbers are only shown in aggregate form.',
    roleLabel: 'Role',
    memberRole: 'Member',
    mentorRole: 'Mentor',
    leaderRole: 'Leader',
    adminRole: 'Administrator',
    groupsLabel: 'groups',
    statsEmpty: 'The first statistics will appear once the community has enough activity.',
    invite: 'Invite my tandem',
    inviteDescription: 'The invitation is private and expires after 7 days.',
    inviteEmail: 'Person’s email',
    createInvite: 'Create invitation',
    inviteCreated: 'Invitation created. You can share this link.',
    copyInvite: 'Copy link',
    inviteRequiresAuth: 'Sign in to create a private invitation.',
    inviteAccepted: 'Invitation accepted. Your tandem is active.',
    inviteAcceptError: 'This invitation is invalid, expired, or reserved for another email.',
    blockedStatus: 'Blocked',
    endedStatus: 'Ended',
    partnerDeleted: 'This account was deleted',
    tandemEndedNote: 'This relationship has ended: no one can write here any more. The messages stay readable, and you can invite someone else whenever you want.',
    blockedNotice: 'This relationship is now blocked.',
    blockRefused: 'The block was not set. Reload the page to see where the relationship stands.',
    unblockRefused: 'The block was not lifted. Reload the page to see where the relationship stands.',
    unblock: 'Lift the block',
    unblockOwnerNote: 'You blocked this relationship. Only you can lift it.',
    unblockOtherNote: 'Your tandem blocked this relationship. Only the person who set the block can lift it.',
    unblockFrozenNote: 'This block was set before our security update: the app no longer knows who set it, so it cannot lift it for anyone. Write to contact@agapeplay.com and someone will take care of it.',
    unblockTitle: 'Lift this block?',
    unblockDescription: 'The conversation becomes possible again both ways: you will be able to write to each other, and the history becomes readable again for both of you.',
    unblockReversible: 'Nothing is final: you can block again whenever you want.',
    unblockConfirm: 'Yes, lift the block',
    unblockCancel: 'No, keep the block',
    unblockedNotice: 'The block is lifted. The conversation resumes.',
    reportSent: 'Report sent to moderation.',
    messageUnavailable: 'The conversation is unavailable right now.',
    offline: 'Offline · changes will sync when you are back online.',

    invitationsKicker: 'Follow-up',
    invitationsTitle: 'Your invitations',
    invitationsDescription: 'What you sent, where it stands, and what you can still take back.',
    invitationsLoading: 'Loading your invitations…',
    invitationsError: 'Your invitations could not be read. Try again in a moment.',
    invitationsRefresh: 'Reload the list',
    invitationsSent: 'Sent',
    invitationsEmpty: 'You have not invited anyone yet.',
    invitationsReceived: 'Received',
    invitationsReceivedOne: 'An invitation is waiting for you.',
    invitationsReceivedHint: 'To accept it, open the link in your email: that is what carries the code.',
    invitationsReceivedNoIdentity: 'An invitation does not say who sent it until it is accepted. The email you received does.',
    invitationStateLive: 'Waiting for an answer',
    invitationStateExpired: 'Expired',
    invitationStateAccepted: 'Accepted',
    invitationStateRevoked: 'Cancelled',
    invitationsSentOn: 'Sent on',
    invitationsExpiresOn: 'Valid until',
    invitationsExpiredOn: 'Expired on',
    invitationsAcceptedOn: 'Accepted on',
    invitationsCancel: 'Cancel this invitation',
    invitationsCancelled: 'Invitation cancelled. The link no longer works.',
    invitationsCancelFailed: 'The invitation could not be cancelled. Reload the list: its state may have changed in the meantime.',
    invitationsExpiredNote: 'This link no longer works. Send a new invitation if you want to try again.',
    invitationsBlockedNote: 'You and this person are blocked from each other: the app can no longer touch this invitation. It leads nowhere — pairing is refused while the block holds — and it will lapse on its own at its date. To take it back, the block has to be lifted first.',

    moderation: 'Moderation',
    moderationTitle: 'Reports',
    moderationDescription: 'What was reported, its context, and nothing else.',
    moderationLoading: 'Loading reports…',
    moderationError: 'Reports could not be read. Try again in a moment.',
    moderationEmpty: 'No report is waiting for a decision.',
    moderationRefresh: 'Reload the list',
    moderationNoIdentity: 'This space never shows the names or accounts of the participants: that is a design decision, not a gap.',
    moderationCount: 'reports',
    moderationOpenCount: 'awaiting a decision',
    statusOpen: 'To handle',
    statusReviewing: 'Taken on',
    statusResolved: 'Closed',
    moderationTake: 'Take this on',
    moderationClose: 'Close the case',
    moderationReopen: 'Reopen the case',
    moderationUpdated: 'Decision recorded.',
    moderationUpdateFailed: 'The decision was not recorded. Your moderation access may have been withdrawn in the meantime.',
    moderationReason: 'What the report says',
    moderationReportedAt: 'Reported on',
    moderationClosedAt: 'Closed on',
    moderationMessage: 'The reported message',
    moderationNoMessage: 'This report does not point at a specific message: it is about the relationship. The rest of the conversation cannot be read from here.',
    moderationFromReporter: 'Written by the person reporting',
    moderationFromOther: 'Written by the other participant',
    moderationContext: 'The relationship',
    moderationNoContext: 'The state of this relationship cannot be read: it was most likely deleted.',
    moderationRelationOpened: 'Opened on',
    moderationRelationBlocked: 'Blocked on',
    moderationRelationEnded: 'Ended on',
    relationActive: 'Active relationship',
    relationBlocked: 'Blocked relationship',
    relationPaused: 'Paused relationship',
    relationEnded: 'Ended relationship',
    moderationTrail: 'Decision log',
    moderationTrailEmpty: 'No decision has been taken on this case yet.',
    moderationTrailNote: 'Only decisions leave a trace. Opening a case leaves none.',
    moderationTrailByMe: 'by you',
    moderationTrailByOther: 'by another moderator',
    moderationTrailUnknown: 'no identified moderator',
  },
} as const

export type Copy = (typeof copy)['fr'] | (typeof copy)['en']
